{% set data = load_setup_py_data() %}

package:
  name: pydlt
  version: {{ data['version'] }}

source:
  git_url: https://github.com/dmarnerides/pydlt.git
  git_rev: master

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  noarch: python
  string: {{ GIT_BUILD_STR }}
  entry_points:
    - dlt-plot = dlt.viz.csvplot:plot_csv
    - dlt-dispatch = dlt.util.dispatch:dispatch

test:
  imports:
    - dlt

about:
  home: https://github.com/dmarnerides/pydlt
  license: BSD
  license_file: LICENSE
