package:
  name: pydlt
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/dmarnerides/pydlt.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  noarch: python
  string: {{ environ['GIT_BUILD_STR'] }}
  entry_points:
    - dlt-plot = dlt.viz.csvplot:plot_csv
    - dlt-dispatch = dlt.util.dispatch:dispatch
  script_env:
   - VERSION
   - GIT_BUILD_STR
   - CONDA_BLD_PATH

test:
  imports:
    - dlt
  script_env:
   - VERSION
   - GIT_BUILD_STR
   - CONDA_BLD_PATH

about:
  home: https://github.com/dmarnerides/pydlt
  license: BSD
  license_file: LICENSE
